server:
  port: 9338
  tomcat:
    basedir: C:/Temp
spring:
  application:
    name: Penetrate
  threads:
    virtual:
      enabled: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 32
        queue-capacity: 1000
      thread-name-prefix: async-task-
    scheduling:
      pool:
        size: 4
      thread-name-prefix: scheduled-task-

nat:
  mode: client  # server, client, or both
  server:
    enabled: false
  client:
    enabled: true
    server-host: 39.104.48.206
    server-port: 61927
    enable-ssl: false
    port-mappings:
      - local-port: 22
        remote-port: 9522
        protocol: tcp
        enabled: true
        max-connections: 100
        connection-timeout: 5000
        idle-timeout: 600
        local-host: 127.0.0.1
      - local-port: 8080
        remote-port: 80
        protocol: tcp
        enabled: true
        max-connections: 100
        connection-timeout: 5000
        idle-timeout: 600
        local-host: 127.0.0.1
    client-id: client001

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always